# Site settings
title:       Gustavo Burin's webpage
email:       arietebio@gmail.com
author:      Gustavo Burin
description: ""
baseurl:     ""
url:         "http://gburin.github.io"

title: Gustavo Burin
email: arietebio@gmail.com
author: Gustavo Burin
description: "Macroevolution, macroecology, open science, and random shenanigans"
baseurl: ""
url: "http://gburin.github.io"
google_analytics: UA-53548208-1

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: gburin
stackoverflow_id:
twitter_username: gustavoburin
google_plus_id: +GustavoBurinFerreira
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
#redcarpet:
#  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true

gems:
  - jekyll-gist 
  - jekyll-paginate
encoding: UTF-8
